version: "3"
services:
  qinglong:
    image: whyour/qinglong:latest
    container_name: qinglong
    restart: unless-stopped
    tty: true
    ports:
      - 5700:5700
    environment:
      - ENABLE_HANGUP=true
      - ENABLE_WEB_PANEL=true
    volumes:
      - ./config:/ql/config
      - ./db:/ql/db
      - ./scripts:/ql/scripts
  xdd:
    image: gcdd1993/xdd:v20210823
    container_name: xdd
    restart: unless-stopped
    tty: true
    ports:
      - 8080:8080
    environment:
      - XDD_REPO_URL=https://ghproxy.com/https://github.com/cdle/xdd
    volumes:
      - ./xdd:/xdd