version: "3"
services:
  qinglong-xdd:
    image: gcdd1993/qinglong-xdd:v2.8.4-002
    container_name: qinglong-xdd
    restart: unless-stopped
    tty: true
    ports:
      - 5700:5700
      - 8080:8080
    environment:
      - ENABLE_HANGUP=true
      - ENABLE_WEB_PANEL=true
      - XDD_RELEASE_URL=https://ghproxy.com/https://github.com/gcdd1993/xdd/releases/download/v20210822/xdd_20210822_Linux_x86_64.tar.gz
    volumes:
      - ./config:/ql/config
      - ./db:/ql/db
      - ./scripts:/ql/scripts
      - ./xdd:/ql/xdd