name: 编译xdd
on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *' #北京时间0点运行，action会有延迟
  watch:
    types: started
  repository_dispatch:
    types: qinglong_xdd
jobs:
  release-linux-386:
    name: release linux/386
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          repository: cdle/xdd
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.7
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
